name: Eslint-chek

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  Eslint:
    runs-on: ubuntu-latest
 
    steps:
      - name: npm install
        # Install project
        run: |
          npm install
        # Add environment variables
        env:
          CI: true
      - name: Run linter
        # Run Linter
        run: |
          make lint